// Command third-party-notices writes THIRD-PARTY-NOTICES.md with the licence text of every linked
// module and copied upstream, as binary distribution requires. -check fails when it is stale.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"github.com/lumioguard/lumioguard-cc/internal/paths"
	"github.com/lumioguard/lumioguard-cc/internal/thirdparty"
)

const (
	outputFile = "THIRD-PARTY-NOTICES.md"
	mainPkg    = "./cmd/lumioguard-cc"
)

var licenceFileNames = []string{"LICENSE", "LICENSE.txt", "LICENSE.md", "LICENCE", "COPYING", "NOTICE.txt"}

type module struct {
	Path    string
	Version string
	Dir     string
}

func main() {
	check := flag.Bool("check", false, "verify the committed file is current instead of writing it")
	flag.Parse()
	if err := run(*check); err != nil {
		fmt.Fprintln(os.Stderr, "third-party-notices:", err)
		os.Exit(1)
	}
}

func run(check bool) error {
	root, err := thirdparty.RepositoryRoot()
	if err != nil {
		return err
	}
	modules, err := linkedModules()
	if err != nil {
		return err
	}
	document, err := render(root, modules)
	if err != nil {
		return err
	}
	document = lf(document)
	path := filepath.Join(root, outputFile)
	if check {
		existing, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("%s is missing; run: go run ./tools/third-party-notices", outputFile)
		}
		if !bytes.Equal(lf(existing), document) {
			return fmt.Errorf("%s is out of date; run: go run ./tools/third-party-notices", outputFile)
		}
		fmt.Printf("%s is current (%d modules, %d copied components)\n", outputFile, len(modules), len(thirdparty.All()))
		return nil
	}
	if err := os.WriteFile(path, document, 0o644); err != nil {
		return err
	}
	fmt.Printf("wrote %s: %d linked modules, %d copied components\n", outputFile, len(modules), len(thirdparty.All()))
	return nil
}

// lf normalises line endings, so upstream CRLF licence files and Windows checkouts
// produce the same bytes everywhere.
func lf(data []byte) []byte {
	return bytes.ReplaceAll(data, []byte("\r\n"), []byte("\n"))
}

// shippedPlatforms are the operating systems the release builds for; a module linked on
// any of them, such as mousetrap on Windows, must appear in the notices.
var shippedPlatforms = []string{"linux", "darwin", "windows"}

// linkedModules lists every module whose code is compiled into a shipped executable, the same
// on every platform. Test-only and tool-only modules are excluded because they are not shipped.
func linkedModules() ([]module, error) {
	seen := map[string]module{}
	for _, goos := range shippedPlatforms {
		cmd := exec.Command("go", "list", "-deps",
			"-f", "{{if and .Module (not .Module.Main)}}{{.Module.Path}}\t{{.Module.Version}}\t{{.Module.Dir}}{{end}}", mainPkg)
		cmd.Env = append(os.Environ(), "GOOS="+goos)
		output, err := cmd.Output()
		if err != nil {
			return nil, fmt.Errorf("list dependencies for %s: %w", goos, err)
		}
		for _, line := range strings.Split(string(output), "\n") {
			fields := strings.Split(strings.TrimSpace(line), "\t")
			if len(fields) != 3 || fields[0] == "" || fields[2] == "" {
				continue
			}
			seen[fields[0]] = module{Path: fields[0], Version: fields[1], Dir: fields[2]}
		}
	}
	modules := make([]module, 0, len(seen))
	for _, m := range seen {
		modules = append(modules, m)
	}
	sort.Slice(modules, func(i, j int) bool { return modules[i].Path < modules[j].Path })
	return modules, nil
}

func render(root string, modules []module) ([]byte, error) {
	var out bytes.Buffer
	out.WriteString("# Third-party notices\n\n")
	out.WriteString("lumioguard CC includes the software listed below. This file reproduces each\n")
	out.WriteString("licence in full, as the BSD and Apache licences require of binary\n")
	out.WriteString("distributions. **Ship it alongside the executable.**\n\n")
	out.WriteString("Generated by `go run ./tools/third-party-notices`; verify with `-check`.\n")
	out.WriteString("lumioguard CC itself is released under the MIT License; see LICENSE.\n\n")

	out.WriteString("## Summary\n\n")
	out.WriteString("| Component | Version | Licence | How it is included |\n| --- | --- | --- | --- |\n")
	for _, component := range thirdparty.All() {
		name := component.Module
		if name == "" {
			name = component.Origin
		}
		fmt.Fprintf(&out, "| %s | `%s` | %s | copied into `%s` |\n",
			name, component.Version, component.License, component.Path)
	}
	for _, m := range modules {
		licence, _, err := licenceOf(m.Dir)
		if err != nil {
			return nil, err
		}
		fmt.Fprintf(&out, "| %s | `%s` | %s | linked Go module |\n", m.Path, m.Version, detect(licence))
	}

	out.WriteString("\n## Copied and generated source\n\n")
	for _, component := range thirdparty.All() {
		fmt.Fprintf(&out, "### %s\n\n", component.Name)
		fmt.Fprintf(&out, "- Upstream: %s\n- Version: `%s`\n- Licence: %s\n- Location in this repository: `%s`\n- Refresh with: `%s`\n\n",
			component.Origin, component.Version, component.License, component.Path, component.SyncTool)
		out.WriteString("Modifications made to the upstream source:\n\n")
		for _, modification := range component.Modifications {
			fmt.Fprintf(&out, "- %s\n", modification)
		}
		out.WriteString("\n")
		for _, name := range []string{"LICENSE", "NOTICE.txt"} {
			path := filepath.Join(paths.Resolve(root, component.Path), name)
			data, err := os.ReadFile(path)
			if err != nil {
				continue
			}
			fmt.Fprintf(&out, "<details><summary>%s: %s</summary>\n\n```\n%s\n```\n\n</details>\n\n",
				component.Path, name, strings.TrimRight(string(lf(data)), "\n"))
		}
	}

	out.WriteString("## Linked Go modules\n\n")
	for _, m := range modules {
		licence, file, err := licenceOf(m.Dir)
		if err != nil {
			return nil, err
		}
		fmt.Fprintf(&out, "### %s %s\n\n%s, from `%s`.\n\n```\n%s\n```\n\n",
			m.Path, m.Version, detect(licence), file, strings.TrimRight(licence, "\n"))
	}
	return out.Bytes(), nil
}

func licenceOf(dir string) (text string, filename string, err error) {
	for _, name := range licenceFileNames {
		data, readErr := os.ReadFile(filepath.Join(dir, name))
		if readErr == nil {
			return string(lf(data)), name, nil
		}
	}
	return "", "", fmt.Errorf("no licence file found in %s", dir)
}

// detect returns the SPDX identifier by matching distinguishing phrases, and reports an
// unknown licence rather than guessing.
func detect(text string) string {
	switch {
	case strings.Contains(text, "Apache License"):
		return "Apache-2.0"
	case strings.Contains(text, "GNU LESSER"), strings.Contains(text, "GNU Lesser"):
		return "LGPL (review before distributing)"
	case strings.Contains(text, "GNU GENERAL"), strings.Contains(text, "GNU General"):
		return "GPL (review before distributing)"
	case strings.Contains(text, "Permission is hereby granted, free of charge"):
		return "MIT"
	case strings.Contains(text, "Redistribution and use"):
		if strings.Contains(text, "endorse or promote") {
			return "BSD-3-Clause"
		}
		return "BSD-2-Clause"
	default:
		return "unrecognised (review manually)"
	}
}
